version: 0.2

phases:
  install:
    runtime-version:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo start prebuild....
  build:
    commands:
      - echo Running unit tests with pytest...
      - pytest --junitxml=reports/results.xml --tb=short
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - "**/*"
  base-directory: . #specifiy where artifacts are stored
reports:
  pytest_reports:
    files:
      - "reports/results.xml"
    discard-paths: yes